### ISSUE TITLE
astro 1.0.0-rc.1

### ISSUE THREAD

**Issue by kaanguru** [littlesticksdev/odyssey-theme#2]
It seems `canonicalURL `changed into `url` so Astro.url must be used 

**odyssey-theme is not working with astro 1.0.0-rc.1**

**Comment by edm00se** [comment]
To that point, [astro 1.0 has been released](https://astro.build/blog/astro-1/).

**Comment by jaydanurwin** [comment]
Thanks for opening this @kaanguru I just released v1.0.0 of the theme with #4 that fixes this among some other upgrades and supports Astro v1.0 🎉
