### ISSUE TITLE
Netlify deploy failing

### ISSUE THREAD

**Issue by mitrick2** [littlesticksdev/odyssey-theme#5]
Launching from this repo directly, I'm getting a build failure. Looks like astro isn't available in deploy sequence?

> 8:43:32 AM: ────────────────────────────────────────────────────────────────
8:43:32 AM:   1. Build command from Netlify app                             
8:43:32 AM: ────────────────────────────────────────────────────────────────
8:43:32 AM: ​
8:43:32 AM: $ npm run build
8:43:32 AM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
8:43:32 AM: npm WARN config location in the cache, and they are managed by
8:43:32 AM: npm WARN config     [`cacache`](http://npm.im/cacache).
8:43:32 AM: > odyssey-theme@1.0.0 build
8:43:32 AM: > astro build
**8:43:32 AM: sh: 1: astro: not found**
8:43:32 AM: ​
8:43:32 AM: ────────────────────────────────────────────────────────────────
8:43:32 AM:   "build.command" failed                                        
8:43:32 AM: ────────────────────────────────────────────────────────────────
8:43:32 AM: ​
8:43:32 AM:   Error message
8:43:32 AM:   Command failed with exit code 127: npm run build (https://ntl.fyi/exit-code-127)

**Comment by l3op** [comment]
> Launching from this repo directly, I'm getting a build failure. Looks like astro isn't available in deploy sequence?
> 
> > 8:43:32 AM: ────────────────────────────────────────────────────────────────
> > 8:43:32 AM:   1. Build command from Netlify app
> > 8:43:32 AM: ────────────────────────────────────────────────────────────────
> > 8:43:32 AM: ​
> > 8:43:32 AM: $ npm run build
> > 8:43:32 AM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
> > 8:43:32 AM: npm WARN config location in the cache, and they are managed by
> > 8:43:32 AM: npm WARN config     [`cacache`](http://npm.im/cacache).
> > 8:43:32 AM: > odyssey-theme@1.0.0 build
> > 8:43:32 AM: > astro build
> > **8:43:32 AM: sh: 1: astro: not found**
> > 8:43:32 AM: ​
> > 8:43:32 AM: ────────────────────────────────────────────────────────────────
> > 8:43:32 AM:   "build.command" failed
> > 8:43:32 AM: ────────────────────────────────────────────────────────────────
> > 8:43:32 AM: ​
> > 8:43:32 AM:   Error message
> > 8:43:32 AM:   Command failed with exit code 127: npm run build (https://ntl.fyi/exit-code-127)

I have this issue also. 

I guess because astro wasn't defined at package.json file in the main directory.
You might need to deploy the theme folder.

**Comment by jaydanurwin** [comment]
@mitrick2 Are you setting the base directory for your Netlify project to the `theme/` folder? This would be necessary for it to deploy the actual site's files instead of the monorepo. I might be able to set up some config for this to be automatic but I'll have to look into that.

**Comment by mitrick2** [comment]
Doh! Once I set the base directory, it worked as expected. Thank you!
